name: titro-app

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes # Enable persistence

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./apps/backend/uploads:/app/uploads
      - ./apps/backend/src:/app/src
      - ./apps/backend/package.json:/app/package.json
      - ./apps/backend/tsconfig.json:/app/tsconfig.json
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "3001:5173"
    environment:
      - VITE_APP_API_URL=http://localhost:3000
    command: npm run dev -- --host

  nginx-proxy:
    profiles: ["disabled"]

  letsencrypt:
    profiles: ["disabled"]

volumes:
  redis-data: # Persistent volume for Redis data
