name: titro-app

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes # Enable persistence

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./apps/backend/uploads:/app/uploads
    depends_on:
      - redis
    environment:
      - LETSENCRYPT_EMAIL=jr.titro.app@mailo.com
      - REDIS_HOST=redis
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_API_URL=https://titro.app # Use HTTPS here
    container_name: frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - LETSENCRYPT_EMAIL=jr.titro.app@mailo.com
      - LETSENCRYPT_HOST=titro.app,www.titro.app
      - VIRTUAL_HOST=titro.app,www.titro.app
      - VIRTUAL_PORT=80
    # Port mapping - uncomment for local development only
    # In production, nginx-proxy will handle the routing based on VIRTUAL_HOST
    # ports:
    #   - "5173:80"  # Map container's 80 port to host's 5173

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./apps/backend/uploads:/app/uploads
    environment:
      - DEFAULT_HOST=titro.app

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=jr.titro.app@mailo.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh

volumes:
  redis-data: # Persistent volume for Redis data
