version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
    environment:
      - LETSENCRYPT_EMAIL=jr.titro.app@mailo.com
      - LETSENCRYPT_HOST=dev.titro.app
      - REDIS_HOST=redis
      - VIRTUAL_HOST=dev.titro.app
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - LETSENCRYPT_EMAIL=jr.titro.app@mailo.com
      - LETSENCRYPT_HOST=www.dev.titro.app
      - VIRTUAL_HOST=www.dev.titro.app
      - VIRTUAL_PORT=5173
      - VITE_APP_API_URL=http://backend:3000
    ports:
      - "5173:5173"

  workers:
    build:
      context: ./workers
      dockerfile: Dockerfile
    container_name: workers
    restart: always
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - redis

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./uploads:/app/uploads
    environment:
      - DEFAULT_HOST=titro.app

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=jr.titro.app@mailo.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
